#!/usr/bin/env python3
"""Export executive_analysis.json to a human-readable Markdown review pack.

This gives the user a clear pre-render view of the intelligence layer: primary
message, findings, risks, actions, presentation plan and the evidence behind
each point.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _evidence_lines(evidence: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for ev in evidence:
        value = ev.get("value")
        unit = ev.get("unit", "")
        value_text = "source-linked" if value is None else f"{value}{unit}"
        lines.append(f"  - Evidence: **{ev.get('label', 'Value')}** = `{value_text}` (`{ev.get('data_ref')}`)")
    return lines


def _insight_block(title: str, items: list[dict[str, Any]]) -> list[str]:
    lines = [f"## {title}", ""]
    if not items:
        lines.extend(["No items generated by the current deterministic rules.", ""])
        return lines

    for item in sorted(items, key=lambda x: x.get("priority", 99)):
        lines.append(f"### P{item.get('priority')} — {item.get('headline')}")
        lines.append(f"- **Interpretation:** {item.get('interpretation')}")
        lines.append(f"- **Business impact:** {item.get('business_impact')}")
        lines.append(f"- **Confidence:** {item.get('confidence')}")
        lines.extend(_evidence_lines(item.get("supporting_evidence", [])))
        lines.append("")
    return lines


def to_markdown(analysis: dict[str, Any]) -> str:
    meta = analysis.get("analysis_meta", {})
    primary = analysis.get("primary_message", {})

    lines = [
        f"# Executive Analysis — {meta.get('source_report_title', 'Untitled report')}",
        "",
        f"- **Report type:** {meta.get('source_report_type', 'unknown')}",
        f"- **Generated from:** `{meta.get('generated_from', '')}`",
        "",
        "## Primary Message",
        "",
        f"### {primary.get('headline', 'No headline')}",
        "",
        primary.get("summary", ""),
        "",
        f"**Confidence:** {primary.get('confidence', 'unknown')}",
        "",
        "### Primary Evidence",
    ]
    lines.extend(_evidence_lines(primary.get("supporting_evidence", [])))
    lines.append("")

    lines.extend(_insight_block("Findings", analysis.get("findings", [])))
    lines.extend(_insight_block("Risks", analysis.get("risks", [])))
    lines.extend(_insight_block("Opportunities", analysis.get("opportunities", [])))
    lines.extend(_insight_block("Recommended Actions", analysis.get("recommended_actions", [])))

    lines.extend(["## Presentation Plan", ""])
    plan = analysis.get("presentation_plan", [])
    if not plan:
        lines.extend(["No presentation plan generated.", ""])
    else:
        for item in sorted(plan, key=lambda x: x.get("priority", 99)):
            lines.append(f"- **P{item.get('priority')} / {item.get('preferred_width', 'half')}** `{item.get('section_id')}` — {item.get('reason')}")
        lines.append("")

    lines.extend(["## Source Values Used", ""])
    source_values = analysis.get("source_values_used", [])
    if not source_values:
        lines.append("No source values listed.")
    else:
        lines.extend(_evidence_lines(source_values))
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("executive_analysis", type=Path)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    analysis = json.loads(args.executive_analysis.read_text())
    output = args.output or args.executive_analysis.with_suffix(".md")
    output.write_text(to_markdown(analysis), encoding="utf-8")
    print(f"EXECUTIVE ANALYSIS MARKDOWN WRITTEN — {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
